// Generated by module-data-generator.cjs
export const people = [
    {
        "id": 1,
        "name": "Kacper",
        "birthDate": "2001-07-05",
        "email": "kacper@wsei.edu.pl",
        "phone": "318-156-889"
    },
    {
        "id": 2,
        "name": "Kacper",
        "birthDate": "2004-09-21",
        "email": "kacper2@wsei.edu.pl",
        "phone": "397-187-241"
    },
    {
        "id": 3,
        "name": "Wiktor",
        "birthDate": "2000-07-11",
        "email": "wiktor@wsei.edu.pl",
        "phone": "474-294-872"
    },
    {
        "id": 4,
        "name": "Wiktor",
        "birthDate": "2004-02-20",
        "email": "wiktor2@wsei.edu.pl",
        "phone": "838-808-400"
    },
    {
        "id": 5,
        "name": "Emilia",
        "birthDate": "2000-07-19",
        "email": "emilia@wsei.edu.pl",
        "phone": "645-825-182"
    },
    {
        "id": 6,
        "name": "Kacper",
        "birthDate": "2005-09-30",
        "email": "kacper3@wsei.edu.pl",
        "phone": "331-192-152"
    },
    {
        "id": 7,
        "name": "Wiktor",
        "birthDate": "2000-11-29",
        "email": "wiktor3@wsei.edu.pl",
        "phone": "118-215-402"
    },
    {
        "id": 8,
        "name": "Wiktor",
        "birthDate": "2001-07-13",
        "email": "wiktor4@wsei.edu.pl",
        "phone": "858-649-428"
    },
    {
        "id": 9,
        "name": "Emilia",
        "birthDate": "2005-06-17",
        "email": "emilia2@wsei.edu.pl",
        "phone": "419-351-607"
    },
    {
        "id": 10,
        "name": "Karol",
        "birthDate": "2001-07-12",
        "email": "karol@wsei.edu.pl",
        "phone": "372-563-403"
    }
];
